import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:osta/core/di/injection.config.dart';

/// Global service locator.
final GetIt getIt = GetIt.instance;

/// Registers every `@injectable` dependency. Generated by `build_runner`.
@InjectableInit()
Future<void> configureDependencies() async {
  getIt.init();
}
