import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Structural invariants the analyzer cannot express.
///
/// Folder reorgs have broken this repo twice (CHANGELOG 2026-07-09): one left
/// two files declaring `MyBookingsScreen` — an ambiguous-import compile error —
/// and another left an identical dead duplicate widget. These tests fail on
/// exactly those shapes, so the next reorg trips a test instead of a build.
void main() {
  final libDart = Directory('lib')
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      // Generated, regenerated by `flutter gen-l10n`, never hand-edited.
      .where((f) => !f.path.startsWith('lib/core/l10n/'))
      .toList();

  test('lib/features holds only the role buckets', () {
    final entries =
        Directory('lib/features')
            .listSync()
            .whereType<Directory>()
            .map((d) => d.path.split('/').last)
            .toList()
          ..sort();

    expect(entries, ['business', 'customer', 'shared']);
  });

  test('roles do not import each other', () {
    final offenders = <String>[];
    for (final file in libDart) {
      final owner = switch (file.path) {
        final p when p.startsWith('lib/features/business/') => 'business',
        final p when p.startsWith('lib/features/customer/') => 'customer',
        _ => null,
      };
      if (owner == null) continue;

      final other = owner == 'business' ? 'customer' : 'business';
      if (file.readAsStringSync().contains('package:osta/features/$other/')) {
        offenders.add('${file.path} imports $other');
      }
    }
    expect(offenders, isEmpty);
  });

  test('no public class name is declared twice', () {
    final declaring = <String, List<String>>{};
    final classRe = RegExp(
      r'^(?:abstract\s+|final\s+|sealed\s+|base\s+|'
      r'interface\s+|mixin\s+)*class\s+(\w+)',
      multiLine: true,
    );

    for (final file in libDart) {
      for (final m in classRe.allMatches(file.readAsStringSync())) {
        final name = m.group(1)!;
        // Private classes are file-scoped, so sharing a name is legal and
        // cannot cause an ambiguous import. Duplicated bodies are a dedup
        // concern, not a correctness one.
        if (name.startsWith('_')) continue;
        (declaring[name] ??= []).add(file.path);
      }
    }

    final dupes = declaring.entries.where((e) => e.value.length > 1).toList();
    expect(
      dupes.map((e) => '${e.key}: ${e.value.join(", ")}'),
      isEmpty,
      reason:
          'Two files declaring one class is the ambiguous-import error '
          'that broke this repo before.',
    );
  });

  test('every l10n key used in lib exists in app_en.arb', () {
    final arb = File('lib/l10n/app_en.arb').readAsStringSync();
    final declared = RegExp(
      r'^\s{2}"(\w+)"\s*:',
      multiLine: true,
    ).allMatches(arb).map((m) => m.group(1)!).toSet();

    final missing = <String>{};
    final useRe = RegExp(r'\bl10n\.(\w+)');
    for (final file in libDart) {
      for (final m in useRe.allMatches(file.readAsStringSync())) {
        final key = m.group(1)!;
        if (!declared.contains(key)) missing.add('${file.path}: $key');
      }
    }
    expect(missing, isEmpty, reason: 'Deleting a live key breaks the build.');
  });
}
